### NumPy Array Shape

In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv("C:/Users/ANJU/Desktop/internship/student data.csv")

arr = np.array(df['Hours'])
arr1= np.array(df['Scores'])

print(arr.shape)
print(arr1.shape)

(25,)
(25,)


In [2]:
print('No of dimensions of the array:',df.ndim)     # .ndim for dimensions
print('Total no of elements of the array:',df.size) # .size for size
print('Shape of the array:',df.shape)

No of dimensions of the array: 2
Total no of elements of the array: 50
Shape of the array: (25, 2)


### NumPy Array Reshaping

In [3]:
arr1 = np.array(df['Hours'])
newarr1 = arr1.reshape(5,5)
arr2 = np.array(df['Scores'])
newarr2 = arr2.reshape(5,5)
print(newarr1)
print(newarr2)

[[2.5 5.1 3.2 8.5 3.5]
 [1.5 9.2 5.5 8.3 2.7]
 [7.7 5.9 4.5 3.3 1.1]
 [8.9 2.5 1.9 6.1 7.4]
 [2.7 4.8 3.8 6.9 7.8]]
[[21 47 27 75 30]
 [20 88 60 81 25]
 [85 62 41 42 17]
 [95 30 24 67 69]
 [30 54 35 76 86]]


### NumPy Sorting and Searching

In [4]:
# NumPy Sorting
arr1 = np.array(df['Hours'])
arr2 = np.array(df['Scores'])
print(np.sort(arr1))
print(np.sort(arr2))

[1.1 1.5 1.9 2.5 2.5 2.7 2.7 3.2 3.3 3.5 3.8 4.5 4.8 5.1 5.5 5.9 6.1 6.9
 7.4 7.7 7.8 8.3 8.5 8.9 9.2]
[17 20 21 24 25 27 30 30 30 35 41 42 47 54 60 62 67 69 75 76 81 85 86 88
 95]


In [5]:
# numpy searching
arr1 = np.array(df['Scores'])
x = np.where(arr1 == 30)
y = np.where(arr1%2 == 0)
z = np.where(arr1%2 == 1)
print(x)
print(y)
print(z)

(array([ 4, 16, 20], dtype=int64),)
(array([ 4,  5,  6,  7, 11, 13, 16, 17, 20, 21, 23, 24], dtype=int64),)
(array([ 0,  1,  2,  3,  8,  9, 10, 12, 14, 15, 18, 19, 22], dtype=int64),)


In [6]:
arr1 = np.array(df['Scores'])
x = np.searchsorted(arr1, 47)
print(x)


18


### Mean, Median, Mode

In [7]:
# Mean
arr=np.array(df['Scores'])
x=np.mean(arr)
print(x)

51.48


In [8]:
#median
import numpy as np
arr=np.array(df['Scores'])
x = np.median(arr)
print(x)

47.0


In [9]:
# mode
from scipy import stats
arr=np.array(df['Scores']) 
x = stats.mode(arr)
print(x)

ModeResult(mode=array([30], dtype=int64), count=array([3]))


In [10]:
# Standard deviation
arr=np.array(df['Scores']) 
x = np.std(arr)
print(x)

24.775988375844868
